In [15]:
df.to_csv(r'C:\Users\Admin\churn-prediction\data\cleaned_churn.csv', index=False)
print("Cleaned data saved! Shape:", df.shape)

Cleaned data saved! Shape: (7043, 20)

In [16]:
import os
files = os.listdir(r'C:\Users\Admin\churn-prediction\data')
print(files)

['.gitkeep', 'cleaned_churn.csv', 'WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

df = pd.read_csv(r'C:\Users\Admin\churn-prediction\data\WA_Fn-UseC_-Telco-Customer-Churn.csv')
print("Shape:", df.shape)

Shape: (7043, 21)

In [10]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print("Missing after conversion:", df['TotalCharges'].isnull().sum())
df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)
print("Missing after fix:", df['TotalCharges'].isnull().sum())

Missing after conversion: 11
Missing after fix: 0

C:\Users\Admin\AppData\Local\Temp\ipykernel_21952\1344248127.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

In [11]:
df.drop('customerID', axis=1, inplace=True)
print("Columns remaining:", df.shape[1])

Columns remaining: 20

In [12]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
print(df['Churn'].value_counts())

Churn
0    5174
1    1869
Name: count, dtype: int64

In [13]:
binary_cols = ['gender', 'Partner', 'Dependents', 'PhoneService',
               'PaperlessBilling', 'MultipleLines']

le = LabelEncoder()
for col in binary_cols:
    df[col] = le.fit_transform(df[col])

print("Binary encoding done!")
df.head(2)

Binary encoding done!

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,0,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0

In [17]:
df = pd.get_dummies(df, columns=[
    'InternetService', 'OnlineSecurity', 'OnlineBackup',
    'DeviceProtection', 'TechSupport', 'StreamingTV',
    'StreamingMovies', 'Contract', 'PaymentMethod'
])

print("Shape after encoding:", df.shape)

Shape after encoding: (7043, 39)

In [18]:
df['revenue_per_tenure'] = df['TotalCharges'] / (df['tenure'] + 1)
print("New feature created!")
df[['TotalCharges', 'tenure', 'revenue_per_tenure']].head()

New feature created!

   TotalCharges  tenure  revenue_per_tenure
0         29.85       1           14.925000
1       1889.50      34           53.985714
2        108.15       2           36.050000
3       1840.75      45           40.016304
4        151.65       2           50.550000

In [19]:
scaler = StandardScaler()
df[['tenure', 'MonthlyCharges', 'TotalCharges', 'revenue_per_tenure']] = scaler.fit_transform(
    df[['tenure', 'MonthlyCharges', 'TotalCharges', 'revenue_per_tenure']]
)
print("Scaling done!")
df.head(2)

Scaling done!

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,PaperlessBilling,MonthlyCharges,TotalCharges,...,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,revenue_per_tenure
0,0,0,1,0,-1.277445,0,1,1,-1.160323,-0.994242,...,False,False,True,False,False,False,False,True,False,-0.757979
1,1,0,0,0,0.066327,1,0,0,-0.259629,-0.173244,...,False,False,False,True,False,False,False,False,True,-0.117801

In [20]:
df.to_csv('../data/cleaned_churn.csv', index=False)
print("Cleaned data saved! Shape:", df.shape)

Cleaned data saved! Shape: (7043, 40)